# Generated by Django 4.2.3 on 2023-07-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('msg', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_id', to='chatapp.allchats')),
            ],
        ),
    ]
